export const ADMIN_SIGNIN = 'ADMIN_SIGNIN';
export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';

export const CAR_ADD = 'CAR_ADD';
export const CAR_EDIT = 'CAR_EDIT';
export const CAR_DELETE = 'CAR_DELETE';

export const FETCH_CAR = 'FETCH_CAR';
export const FETCH_CAR_DEALER = 'FETCH_CAR_DEALER';

export const FETCH_CAR_BILLING_ALL = 'FETCH_CAR_BILLING_ALL';
export const FETCH_CAR_BILLING_COUNT = 'FETCH_CAR_BILLING_COUNT';
export const FETCH_CAR_BILLING_TOTAL = 'FETCH_CAR_BILLING_TOTAL';

export const FETCH_USER = 'FETCH_USER';
export const EDIT_USER = 'EDIT_USER';

export const FLIGHT_ADD = 'FLIGHT_ADD';
export const FLIGHT_EDIT = 'FLIGHT_EDIT';
export const FLIGHT_DELETE = 'FLIGHT_DELETE';
export const FETCH_FLIGHT = 'FETCH_FLIGHT';
export const FETCH_AIRPORT = 'FETCH_AIRPORT';
export const FETCH_AIRLINE = 'FETCH_AIRLINE';