export const ADMIN_SIGNIN = 'ADMIN_SIGNIN';
export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';

export const CAR_ADD = 'CAR_ADD';
export const CAR_EDIT = 'CAR_EDIT';
export const CAR_DELETE = 'CAR_DELETE';

export const FETCH_CAR = 'FETCH_CAR';
export const FETCH_CAR_DEALER = 'FETCH_CAR_DEALER';

export const FETCH_CAR_BILLING_ALL = 'FETCH_CAR_BILLING_ALL';
export const FETCH_CAR_BILLING_COUNT = 'FETCH_CAR_BILLING_COUNT';
export const FETCH_CAR_BILLING_TOTAL = 'FETCH_CAR_BILLING_TOTAL';

