module.exports = {
  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_IN_TOKEN: 'USER_SIGN_IN_TOKEN',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  FETCH_USER_ABOUT: 'FETCH_USER_ABOUT',
  FETCH_USER_INTEREST: 'FETCH_USER_INTEREST',
  UPDATE_USER_ABOUT: 'UPDATE_USER_ABOUT',
  UPDATE_USER_INTEREST: 'UPDATE_USER_INTEREST',

};
